spring.cloud.gateway.routes[0].id=ms-carrito
spring.cloud.gateway.routes[0].uri=http://ms-carrito:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/carrito/**

spring.cloud.gateway.routes[1].id=ms-categorias
spring.cloud.gateway.routes[1].uri=http://ms-categorias:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.routes[2].id=ms-envios
spring.cloud.gateway.routes[2].uri=http://ms-envios:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/envios/**

spring.cloud.gateway.routes[3].id=ms-inventario
spring.cloud.gateway.routes[3].uri=http://ms-inventario:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.routes[4].id=ms-pagos
spring.cloud.gateway.routes[4].uri=http://ms-pagos:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.routes[5].id=ms-pedidos
spring.cloud.gateway.routes[5].uri=http://ms-pedidos:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.routes[6].id=ms-productos
spring.cloud.gateway.routes[6].uri=http://ms-productos:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.routes[7].id=ms-resenas
spring.cloud.gateway.routes[7].uri=http://ms-resenas:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/resenas/**

spring.cloud.gateway.routes[8].id=ms-tallas
spring.cloud.gateway.routes[8].uri=http://ms-tallas:8089
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/tallas/**

spring.cloud.gateway.routes[9].id=ms-usuarios
spring.cloud.gateway.routes[9].uri=http://ms-usuarios:8090
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[10].id=ms-usuarios-auth
spring.cloud.gateway.routes[10].uri=http://ms-usuarios:8090
spring.cloud.gateway.routes[10].predicates[0]=Path=/auth/**