spring:
  application:
    name: ms-pedidos
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8086

ms:
  usuarios:
    url: ${MS_USUARIOS_URL:http://localhost:8090}
  carrito:
    url: ${MS_CARRITO_URL:http://localhost:8081}
  inventario:
    url: ${MS_INVENTARIO_URL:http://localhost:8084}
  pagos:
    url: ${MS_PAGOS_URL:http://localhost:8085}
  envios:
    url: ${MS_ENVIOS_URL:http://localhost:8083}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3312/pedidos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-pedidos:3306/pedidos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

---
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true