CREATE TABLE IF NOT EXISTS resenas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    calificacion INT NOT NULL,
    comentario VARCHAR(500) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'ACTIVO'
);