CREATE TABLE IF NOT EXISTS pedido (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    estado ENUM('PENDIENTE','CONFIRMADO','ENVIADO','ENTREGADO','CANCELADO') NOT NULL DEFAULT 'PENDIENTE',
    total DECIMAL(10,2) NOT NULL,
    direccion_entrega VARCHAR(255) NOT NULL,
    fecha_pedido DATETIME NOT NULL,
    fecha_actualizacion DATETIME NOT NULL
);

