CREATE TABLE IF NOT EXISTS carrito (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    fecha_creacion DATETIME NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

